### ISSUE TITLE
"_extract_tar: skipping link with missing target:" when extracting image

### ISSUE THREAD

**Issue by pombredanne** [nexB/container-inspector#44]
From https://github.com/nexB/scancode.io/issues/471

While scanning docker://quay.io/wire/alpine-deps  I get this :
> _extract_tar: skipping link with missing target: <TarInfo 'bin/arch' at 0x7ffa99193d00>: Traceback (most recent call last):
> File "/usr/local/lib/python3.9/site-packages/container_inspector/utils.py", line 120, in extract_tar target = tarball._find_link_target(tarinfo)
> File "/usr/local/lib/python3.9/tarfile.py", line 2418, in _find_link_target raise KeyError("linkname %r not found" % linkname) KeyError: "linkname 'bin//bin/busybox' not found" _extract_tar: skipping link with missing target: <TarInfo 'bin/ash' at 0x7ffa99193dc0>: Traceback (most recent call last):
> File "/usr/local/lib/python3.9/site-packages/container_inspector/utils.py", line 120, in extract_tar target = tarball._find_link_target(tarinfo)
> File "/usr/local/lib/python3.9/tarfile.py", line 2418, in _find_link_target raise KeyError("linkname %r not found" % linkname) KeyError: "linkname 'bin//bin/busybox' not found" _extract_tar: skipping link with missing target: <TarInfo 'bin/base64' at 0x7ffa99193b80>: Traceback (most recent call last):
> File "/usr/local/lib/python3.9/site-packages/container_inspector/utils.py", line 120, in extract_tar target = tarball._find_link_target(tarinfo)
> File "/usr/local/lib/python3.9/tarfile.py", line 2418, in _find_link_target raise KeyError("linkname %r not found" % linkname) KeyError: "linkname 'bin//bin/busybox' not found" _extract_tar: skipping link with missing target: <TarInfo 'bin/bbconfig' at 0x7ffa99193e80>: Traceback (most recent call last):
> File "/usr/local/lib/python3.9/site-packages/container_inspector/utils.py", line 120, in extract_tar target = tarball._find_link_target(tarinfo)
>

**Comment by pombredanne** [comment]
To reproduce:
```
docker pull quay.io/wire/alpine-deps
docker save quay.io/wire/alpine-deps > alpine-deps.tar
container_inspector alpine-deps.tar
```
but I cannot get error messages unless I turn on debugging using the latest code.
But there is definitely something fishy... we purposely fail to extract links when links and their target are out of order in the tar (e.f. the target before the link) 

I am adding tests and a new implementation.
